### ISSUE TITLE
Directly inheriting from ActiveRecord::Migration is not supported

### ISSUE THREAD

**Issue by belgoros** [doorkeeper-gem/doorkeeper#1014]
When using Rails `5.1.4` in a Rails API application, the following error happens when running the doorkeeper migration:
```
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateDoorkeeperTables < ActiveRecord::Migration[4.2]
/Users/Serguei/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:525:in `inherited'
/Users/Serguei/projects/rails/fake-api/db/migrate/20180111083011_create_doorkeeper_tables.rb:1:in `<top (required)>'
/Users/Serguei/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/Users/Serguei/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/Users/Serguei/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/Serguei/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/Users/Serguei/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:962:in `load_migration'
/Users/Serguei/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:958:in `migration'
....
```
Here is the generated migration:
```
class CreateDoorkeeperTables < ActiveRecord::Migration
  def change
    create_table :oauth_applications do |t|
      t.string  :name,         null: false
      t.string  :uid,          null: false
      t.string  :secret,       null: false
      t.text    :redirect_uri, null: false
      t.string  :scopes,       null: false, default: ''
      t.timestamps             null: false
    end
...
```
After modifying as below, it worked:
```
class CreateDoorkeeperTables < ActiveRecord::Migration[5.1]
...
```

**Comment by nbulaj** [comment]
It was fixed somewhere in latest PRs, but current maintainer @maclover7 seems to be not interested in project anymore :(

**Comment by belgoros** [comment]
@nbulaj [this one](https://github.com/doorkeeper-gem/doorkeeper/pull/985), I suppose, but it has not been merged yet :(

**Comment by nbulaj** [comment]
Yep, this one. I created a new issue #1021, don't sure maintainer still works on this gem - I can't get any answer from him for my offer of help (I worked on some Doorkeeper features in the past). So don't sure how fast it will be merged and released.

**Comment by belgoros** [comment]
OK, no worries. Double of https://github.com/doorkeeper-gem/doorkeeper/pull/985
