### ISSUE TITLE
Semantic Logger and Doorkeeper::TokensController

### ISSUE THREAD

**Issue by eliang** [doorkeeper-gem/doorkeeper#1061]
I'm running into an exception every time I POST /oauth/tokens.  I have Devise and SemanticLogger installed in a project and would like the tokens controller to play nice with the logger.  I noticed that the Doorkeeper::TokensController is extended from Doorkeeper::ApplicationMetalController, and would like to know the best way to enable logging.

```
Rails -- Could not log "start_processing.action_controller" event. NoMethodError: undefined method `info' for nil:NilClass ["/.rvm/gems/ruby-2.3.3@bdsm/gems/rails_semantic_logger-4.1.3/lib/rails_semantic_logger/extensions/action_controller/log_subscriber_processing.rb:8:in `start_processing'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/activesupport-4.2.6/lib/active_support/subscriber.rb:100:in `finish'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/activesupport-4.2.6/lib/active_support/log_subscriber.rb:83:in `finish'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/activesupport-4.2.6/lib/active_support/notifications/fanout.rb:102:in `finish'" "/.rvm/gems/ruby-2.3.3@bdsm/gems/activesupport-4.2.6/lib/active_support/notifications/fanout.rb:46:in `block in finish'" "/.rvm/gems/ruby-2.3.3@bdsm/gems/activesupport-4.2.6/lib/active_support/notifications/fanout.rb:46:in `each'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/activesupport-4.2.6/lib/active_support/notifications/fanout.rb:46:in `finish'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:36:in `finish'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:25:in `instrument'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `instrument'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:28:in `process_action'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/actionpack-4.2.6/lib/action_controller/metal/rendering.rb:10:in `process_action'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/actionpack-4.2.6/lib/abstract_controller/base.rb:137:in `process'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/actionpack-4.2.6/lib/action_controller/metal.rb:196:in `dispatch'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/actionpack-4.2.6/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/actionpack-4.2.6/lib/action_controller/metal.rb:237:in `block in action'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:43:in `serve'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:43:in `block in serve'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:30:in `each'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:30:in `serve'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:817:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/rack_set_request_id-0.2.0/lib/rack/set_request_id/middleware.rb:17:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/rack-1.6.4/lib/rack/conditionalget.rb:38:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/actionpack-4.2.6/lib/action_dispatch/middleware/params_parser.rb:27:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/actionpack-4.2.6/lib/action_dispatch/middleware/flash.rb:260:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/actionpack-4.2.6/lib/action_dispatch/middleware/cookies.rb:560:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/activerecord-4.2.6/lib/active_record/migration.rb:377:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/actionpack-4.2.6/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:88:in `__run_callbacks__'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/actionpack-4.2.6/lib/action_dispatch/middleware/callbacks.rb:27:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/actionpack-4.2.6/lib/action_dispatch/middleware/reloader.rb:73:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/actionpack-4.2.6/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/better_errors-2.1.1/lib/better_errors/middleware.rb:84:in `protected_app_call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/better_errors-2.1.1/lib/better_errors/middleware.rb:79:in `better_errors_call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/better_errors-2.1.1/lib/better_errors/middleware.rb:57:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/actionpack-4.2.6/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/actionpack-4.2.6/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/railties-4.2.6/lib/rails/rack/logger.rb:38:in `call_app'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/railties-4.2.6/lib/rails/rack/logger.rb:20:in `block in call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/semantic_logger-4.2.0/lib/semantic_logger/semantic_logger.rb:299:in `fast_tag'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/semantic_logger-4.2.0/lib/semantic_logger/base.rb:190:in `tagged'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/railties-4.2.6/lib/rails/rack/logger.rb:20:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/request_store-1.3.1/lib/request_store/middleware.rb:9:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/actionpack-4.2.6/lib/action_dispatch/middleware/request_id.rb:21:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/activesupport-4.2.6/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/actionpack-4.2.6/lib/action_dispatch/middleware/static.rb:120:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/actionpack-4.2.6/lib/action_dispatch/middleware/ssl.rb:24:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/sentry-raven-2.7.1/lib/raven/integrations/rack.rb:51:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/secure_headers-3.7.1/lib/secure_headers/middleware.rb:12:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/railties-4.2.6/lib/rails/engine.rb:518:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/railties-4.2.6/lib/rails/application.rb:165:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/rack-reverse-proxy-0.12.0/lib/rack_reverse_proxy/roundtrip.rb:19:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/rack-reverse-proxy-0.12.0/lib/rack_reverse_proxy/middleware.rb:25:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/bundler/gems/client_ruby-726512562b35/lib/prometheus/middleware/exporter.rb:32:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/bundler/gems/client_ruby-726512562b35/lib/prometheus/middleware/collector.rb:37:in `block in call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/bundler/gems/client_ruby-726512562b35/lib/prometheus/middleware/collector.rb:85:in `trace'"
 "/.rvm/gems/ruby-2.3.3@bdsm/bundler/gems/client_ruby-726512562b35/lib/prometheus/middleware/collector.rb:37:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/puma-3.9.1/lib/puma/configuration.rb:224:in `call'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/puma-3.9.1/lib/puma/server.rb:602:in `handle_request'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/puma-3.9.1/lib/puma/server.rb:435:in `process_client'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/puma-3.9.1/lib/puma/server.rb:299:in `block in run'"
 "/.rvm/gems/ruby-2.3.3@bdsm/gems/puma-3.9.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'"
```

Rails version: 4.2.7
Ruby version: 2.3.3
Doorkeeper version: 4.2.6
Semantic Logger version: 4.2.0

Thanks!

**Comment by nbulaj** [comment]
Hi @eliang . Could you please provide your Doorkeeper initializer content? 

Also do you configured right your SemanticLogger? I don't see any errors from doorkeeper in the backtrace, but I see no `info` method for `nil` class, that seems to be like no logger object provided (as `info` method is a logger method).

**Comment by eliang** [comment]
Here's my doorkeeper initializer.

```
Doorkeeper.configure do
  #Devise::Doorkeeper.configure_doorkeeper(self)
  # Change the ORM that doorkeeper will use (needs plugins)
  orm :active_record

  # This block will be called to check whether the resource owner is authenticated or not.
  resource_owner_authenticator do
    current_user || warden.authenticate!(:scope => :user)
  end

  resource_owner_from_credentials do |_routes|
    u = User.find_for_database_authentication(:email => params[:username])
    u if u && u.valid_password?(params[:password])
  end

  # If you want to restrict access to the web interface for adding oauth authorized applications, you need to declare the block below.
  admin_authenticator do
    # Put your admin authentication logic here.
    # Example implementation:
    current_user.try(:has_any_role?, :support, :admin, :app_owner)  || redirect_to(new_user_session_url)
  end

  # Authorization Code expiration time (default 10 minutes).
  # authorization_code_expires_in 10.minutes

  # Access token expiration time (default 2 hours).
  # If you want to disable expiration, set this to nil.
  access_token_expires_in 2.hours

  # Assign a custom TTL for implicit grants.
  # custom_access_token_expires_in do |oauth_client|
  #   oauth_client.application.additional_settings.implicit_oauth_expiration
  # end

  # Use a custom class for generating the access token.
  # https://github.com/doorkeeper-gem/doorkeeper#custom-access-token-generator
  access_token_generator "::Doorkeeper::JWT"

  # Reuse access token for the same resource owner within an application (disabled by default)
  # Rationale: https://github.com/doorkeeper-gem/doorkeeper/issues/383
  reuse_access_token

  # Issue access tokens with refresh token (disabled by default)
  use_refresh_token

  # Provide support for an owner to be assigned to each registered application (disabled by default)
  # Optional parameter :confirmation => true (default false) if you want to enforce ownership of
  # a registered application
  # Note: you must also run the rails g doorkeeper:application_owner generator to provide the necessary support
  enable_application_owner :confirmation => true

  # Define access token scopes for your provider
  # For more information go to
  # https://github.com/doorkeeper-gem/doorkeeper/wiki/Using-Scopes
  default_scopes :read
  optional_scopes :images, :assessments, :adt, :visits

  # Change the way client credentials are retrieved from the request object.
  # By default it retrieves first from the `HTTP_AUTHORIZATION` header, then
  # falls back to the `:client_id` and `:client_secret` params from the `params` object.
  # Check out the wiki for more information on customization
  # client_credentials :from_basic, :from_params

  # Change the way access token is authenticated from the request object.
  # By default it retrieves first from the `HTTP_AUTHORIZATION` header, then
  # falls back to the `:access_token` or `:bearer_token` params from the `params` object.
  # Check out the wiki for more information on customization
  # access_token_methods :from_bearer_authorization, :from_access_token_param, :from_bearer_param
  access_token_methods :from_bearer_authorization

  # Change the native redirect uri for client apps
  # When clients register with the following redirect uri, they won't be redirected to any server and the authorization code will be displayed within the provider
  # The value can be any string. Use nil to disable this feature. When disabled, clients must provide a valid URL
  # (Similar behaviour: https://developers.google.com/accounts/docs/OAuth2InstalledApp#choosingredirecturi)
  #
  # native_redirect_uri 'urn:ietf:wg:oauth:2.0:oob'

  # Forces the usage of the HTTPS protocol in non-native redirect uris (enabled
  # by default in non-development environments). OAuth2 delegates security in
  # communication to the HTTPS protocol so it is wise to keep this enabled.
  #
  # force_ssl_in_redirect_uri !Rails.env.development?

  # Specify what grant flows are enabled in array of Strings. The valid
  # strings and the flows they enable are:
  #
  # "authorization_code" => Authorization Code Grant Flow
  # "implicit"           => Implicit Grant Flow
  # "password"           => Resource Owner Password Credentials Grant Flow
  # "client_credentials" => Client Credentials Grant Flow
  #
  # If not specified, Doorkeeper enables authorization_code and
  # client_credentials.
  #
  # implicit and password grant flows have risks that you should understand
  # before enabling:
  #   http://tools.ietf.org/html/rfc6819#section-4.4.2
  #   http://tools.ietf.org/html/rfc6819#section-4.4.3
  #
  grant_flows %w[password authorization_code client_credentials]

  # Under some circumstances you might want to have applications auto-approved,
  # so that the user skips the authorization step.
  # For example if dealing with a trusted application.
  # skip_authorization do |resource_owner, client|
  #   client.superapp? or resource_owner.admin?
  # end

  # WWW-Authenticate Realm (default "Doorkeeper").
end
```

I was able to workaround the error by monkey patching Doorkeeper::ApplicationMetalController to the following:

```
class Doorkeeper::ApplicationMetalController < ActionController::Base
  include Doorkeeper::Helpers::Controller
end
```

I understand that the whole point of using the Metal controller was to improve performance, so I am wondering if there's better way to go about this?

Thanks!

**Comment by eliang** [comment]
There must be something else missing from `ActionController::Base` then.

I was hoping this was an already solved issue since I'm not that familiar with the internals of ActionController.

**Comment by nbulaj** [comment]
Try to add `AbstractController::Logger` to `Doorkeeper::ApplicationMetalController` in initializer:

```ruby
Doorkeeper.configure do
 # ...
end

Doorkeeper::ApplicationMetalController.send(:include, AbstractController::Logger)
```

This will add logger accessor to controller. Do'nt sure if SemanticLogger will add it's own logger there, but try to. Also do you use [rails_semantic_logger](https://github.com/rocketjob/rails_semantic_logger) ?

**Comment by eliang** [comment]
Thank you for the snippet.  I tried it but it didn't work.  

I am using rails_semantic_logger and I've added a breakpoint to the [log_subscriber_processing.rb:8](https://github.com/rocketjob/rails_semantic_logger/blob/fc86ef4c7c037a59d3865f302322ce8e462dcb82/lib/rails_semantic_logger/extensions/action_controller/log_subscriber_processing.rb#L18) line in the stack trace.  I see that Semantic Logger is trying to call `controller.constantize.logger` on `"Doorkeeper::TokensController"`, but it returns nil.  It's almost like the controller is not inheriting the default Rails.logger.  I see that both the `AbstractController::Logger` and `ActiveSupport::Notifications` modules implement the `logger` method, but how do you get the `.logger` method to return the Rails.logger?

**Comment by eliang** [comment]
I found that this does the trick...however it's an ugly solution.

```
module Doorkeeper
  class ApplicationMetalController < ActionController::Metal
    MODULES = [
      ActionController::Instrumentation,
      AbstractController::Rendering,
      ActionController::Rendering,
      ActionController::Renderers::All,
      Helpers::Controller
    ].freeze

    MODULES.each do |mod|
      include mod
    end

    ActiveSupport.run_load_hooks(:doorkeeper_metal_controller, self)

    def self.logger
      ActionController::Base.logger
    end
  end
end
```

**Comment by eliang** [comment]
Thanks for all your help @nbulaj!  I'll close this and track the issue in the rails_semantic_logger project.

**Comment by eliang** [comment]
Btw, as of today, the patch still doesn't work.
