### ISSUE TITLE
NoMethodError in Doorkeeper::TokensController#create undefined method `id' for true:TrueClass

### ISSUE THREAD

**Issue by smakman** [doorkeeper-gem/doorkeeper#126]
When requesting an access token with the client credentials flow I get the following error:

```
NoMethodError in Doorkeeper::TokensController#create undefined method `id' for true:TrueClass

doorkeeper (0.4.2) lib/doorkeeper/oauth/password_access_token_request.rb:95:in `create_access_token'
doorkeeper (0.4.2) lib/doorkeeper/oauth/password_access_token_request.rb:79:in `find_or_create_access_token'
doorkeeper (0.4.2) lib/doorkeeper/oauth/password_access_token_request.rb:35:in `authorize'
```

**Comment by ayushyd** [comment]
how i do this in u mean's to say in config/intialize/doorkeeper.rb
