### ISSUE TITLE
Sass::SyntaxError on asset:precompile

### ISSUE THREAD

**Issue by venky-dreamorbit** [doorkeeper-gem/doorkeeper#1342]
I am getting the following error on cap deploy, can you please help?
Ruby Version 2.2.10

```
Sass::SyntaxError: Invalid CSS after ":root{-": expected number or function, was "-blue:#007bff;-..."
  (in /home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/doorkeeper-5.0.2/app/assets/stylesheets/doorkeeper/admin/application.css)
(sass):7
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sass-3.2.19/lib/sass/scss/parser.rb:1147:in `expected'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sass-3.2.19/lib/sass/scss/parser.rb:1085:in `expected'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sass-3.2.19/lib/sass/scss/parser.rb:1067:in `expr!'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sass-3.2.19/lib/sass/scss/parser.rb:922:in `term'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sass-3.2.19/lib/sass/scss/parser.rb:897:in `expr'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sass-3.2.19/lib/sass/scss/parser.rb:671:in `simple_selector_sequence'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sass-3.2.19/lib/sass/scss/parser.rb:640:in `_selector'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sass-3.2.19/lib/sass/scss/parser.rb:619:in `selector'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sass-3.2.19/lib/sass/scss/parser.rb:603:in `selector_sequence'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sass-3.2.19/lib/sass/scss/parser.rb:528:in `ruleset'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sass-3.2.19/lib/sass/scss/parser.rb:591:in `block in declaration_or_ruleset'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sass-3.2.19/lib/sass/scss/parser.rb:1123:in `call'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sass-3.2.19/lib/sass/scss/parser.rb:1123:in `rethrow'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sass-3.2.19/lib/sass/scss/parser.rb:592:in `declaration_or_ruleset'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sass-3.2.19/lib/sass/scss/parser.rb:554:in `block_child'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sass-3.2.19/lib/sass/scss/parser.rb:543:in `block_contents'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sass-3.2.19/lib/sass/scss/parser.rb:535:in `block'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sass-3.2.19/lib/sass/scss/parser.rb:529:in `ruleset'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sass-3.2.19/lib/sass/scss/parser.rb:553:in `block_child'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sass-3.2.19/lib/sass/scss/parser.rb:543:in `block_contents'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sass-3.2.19/lib/sass/scss/parser.rb:82:in `stylesheet'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sass-3.2.19/lib/sass/scss/parser.rb:27:in `parse'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sass-3.2.19/lib/sass/engine.rb:342:in `_to_tree'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sass-3.2.19/lib/sass/engine.rb:315:in `_render'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sass-3.2.19/lib/sass/engine.rb:262:in `render'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.5/lib/sprockets/sass_compressor.rb:24:in `evaluate'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.5/lib/sprockets/context.rb:197:in `block in evaluate'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.5/lib/sprockets/context.rb:194:in `each'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.5/lib/sprockets/context.rb:194:in `evaluate'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.5/lib/sprockets/bundled_asset.rb:25:in `initialize'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.5/lib/sprockets/base.rb:377:in `new'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.5/lib/sprockets/base.rb:377:in `build_asset'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.5/lib/sprockets/index.rb:94:in `block in build_asset'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.5/lib/sprockets/caching.rb:58:in `cache_asset'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.5/lib/sprockets/index.rb:93:in `build_asset'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.5/lib/sprockets/base.rb:287:in `find_asset'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.5/lib/sprockets/index.rb:61:in `find_asset'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.5/lib/sprockets/manifest.rb:211:in `block in find_asset'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.5/lib/sprockets/manifest.rb:257:in `benchmark'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.5/lib/sprockets/manifest.rb:210:in `find_asset'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.5/lib/sprockets/manifest.rb:119:in `block in compile'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.5/lib/sprockets/manifest.rb:118:in `each'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.5/lib/sprockets/manifest.rb:118:in `compile'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sprockets-2.12.5/lib/rake/sprocketstask.rb:146:in `with_logger'
/home/deployer/apps/<app_name>/shared/bundle/ruby/2.2.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
/usr/local/rbenv/versions/2.2.10/bin/bundle:23:in `load'
/usr/local/rbenv/versions/2.2.10/bin/bundle:23:in `<main>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
rake stderr: Nothing written
```

**Comment by venky-dreamorbit** [comment]
Never mind, fixed it with older version of doorkeeper

**Comment by dramalho** [comment]
well, fact is it's broken , just got that one now. We don't need the bundled css files, I'll look for ways to skip them

**Comment by nbulaj** [comment]
Hi @dramalho . It's strange, but I think they can appear in the bundle only if you required them to be there :thinking: 

Anyway, if you have some common solution - please let me know or propose a PR. Thanks!

**Comment by venky-dreamorbit** [comment]
I too had same doubt and checked the assets pipeline, it is not present.

**Comment by dramalho** [comment]
yeah, no luck so far, I'm on an old stack, Rails 4.2 && Sprockets < 4 , so I know Doorkeeper isn't adding them to the precompile list - I'm assuming sprockets just grabs everything it can and throws it into the manifest though . 

Really weird, trying to find a way to have sprockets not precompile those files

**Comment by nbulaj** [comment]
@dramalho latest versions of Doorkeeper don't support Rails < 5.0, so the only solution is to use the old version :(

**Comment by dramalho** [comment]
5.0.2 still did :) - well, the dependencies all worked out, is what I mean .

ok, 5.x is forbidden territory then, no worries

**Comment by dramalho** [comment]
thank you for back-porting the security fixes though , that was great and it means this isn't too much of an issue right now, we'll upgrade our stack soon .

thanks guys
