### ISSUE TITLE
/oauth/token refresh_token hangs Puma and Rails

### ISSUE THREAD

**Issue by sradu** [doorkeeper-gem/doorkeeper#1591]
### Steps to reproduce

I have a NextJS app connecting to a Rails server using Doorkeeper for authentication. NextJS uses SWR which makes a lot of fast requests to Rails to fetch information, plus a call to /oauth/token with a 'refresh_token' to update its access_token.

The puma process that handles the /oauth/token refresh_token POST hangs. pkill -SIGINFO returns this information. Sorry that the message is on one line.

```
[34180] ["  /Home/.rvm/gems/ruby-3.0.1/gems/responders-3.0.1/lib/responders/controller_method.rb:41:in `block in <main>'", "  /Home/.rvm/gems/ruby-3.0.1/gems/activesupport-7.0.4/lib/active_support/lazy_load_hooks.rb:95:in `class_eval'", "  /Home/.rvm/gems/ruby-3.0.1/gems/activesupport-7.0.4/lib/active_support/lazy_load_hooks.rb:95:in `block in execute_hook'", "  /Home/.rvm/gems/ruby-3.0.1/gems/activesupport-7.0.4/lib/active_support/lazy_load_hooks.rb:85:in `with_execution_control'", "  /Home/.rvm/gems/ruby-3.0.1/gems/activesupport-7.0.4/lib/active_support/lazy_load_hooks.rb:90:in `execute_hook'", "  /Home/.rvm/gems/ruby-3.0.1/gems/activesupport-7.0.4/lib/active_support/lazy_load_hooks.rb:76:in `block in run_load_hooks'", "  /Home/.rvm/gems/ruby-3.0.1/gems/activesupport-7.0.4/lib/active_support/lazy_load_hooks.rb:75:in `each'", "  /Home/.rvm/gems/ruby-3.0.1/gems/activesupport-7.0.4/lib/active_support/lazy_load_hooks.rb:75:in `run_load_hooks'", "  /Home/.rvm/gems/ruby-3.0.1/gems/actionpack-7.0.4/lib/action_controller/api.rb:148:in `<class:API>'", "  /Home/.rvm/gems/ruby-3.0.1/gems/actionpack-7.0.4/lib/action_controller/api.rb:89:in `<module:ActionController>'", "  /Home/.rvm/gems/ruby-3.0.1/gems/actionpack-7.0.4/lib/action_controller/api.rb:7:in `<main>'", "  /Home/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'", "  /Home/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'", "  /Home/.rvm/gems/ruby-3.0.1/gems/zeitwerk-2.6.1/lib/zeitwerk/kernel.rb:35:in `require'", "  /Home/.rvm/gems/ruby-3.0.1/gems/activesupport-7.0.4/lib/active_support/inflector/methods.rb:280:in `const_get'", "  /Home/.rvm/gems/ruby-3.0.1/gems/activesupport-7.0.4/lib/active_support/inflector/methods.rb:280:in `constantize'", "  /Home/.rvm/gems/ruby-3.0.1/gems/activesupport-7.0.4/lib/active_support/core_ext/string/inflections.rb:74:in `constantize'", "  /Home/.rvm/gems/ruby-3.0.1/gems/doorkeeper-5.6.0/lib/doorkeeper/config.rb:534:in `resolve_controller'", "  /Home/.rvm/gems/ruby-3.0.1/gems/doorkeeper-5.6.0/app/controllers/doorkeeper/application_metal_controller.rb:5:in `<module:Doorkeeper>'", "  /Home/.rvm/gems/ruby-3.0.1/gems/doorkeeper-5.6.0/app/controllers/doorkeeper/application_metal_controller.rb:3:in `<main>'", "  /Home/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'", "  /Home/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'", "  /Home/.rvm/gems/ruby-3.0.1/gems/zeitwerk-2.6.1/lib/zeitwerk/kernel.rb:27:in `require'", "  /Home/.rvm/gems/ruby-3.0.1/gems/doorkeeper-5.6.0/app/controllers/doorkeeper/tokens_controller.rb:4:in `<module:Doorkeeper>'", "  /Home/.rvm/gems/ruby-3.0.1/gems/doorkeeper-5.6.0/app/controllers/doorkeeper/tokens_controller.rb:3:in `<main>'", "  /Home/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'", "  /Home/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'", "  /Home/.rvm/gems/ruby-3.0.1/gems/zeitwerk-2.6.1/lib/zeitwerk/kernel.rb:27:in `require'", "  /Home/.rvm/gems/ruby-3.0.1/gems/activesupport-7.0.4/lib/active_support/inflector/methods.rb:280:in `const_get'", "  /Home/.rvm/gems/ruby-3.0.1/gems/activesupport-7.0.4/lib/active_support/inflector/methods.rb:280:in `constantize'", "  /Home/.rvm/gems/ruby-3.0.1/gems/activesupport-7.0.4/lib/active_support/core_ext/string/inflections.rb:74:in `constantize'", "  /Home/.rvm/gems/ruby-3.0.1/gems/actionpack-7.0.4/lib/action_dispatch/http/request.rb:90:in `controller_class_for'", "  /Home/.rvm/gems/ruby-3.0.1/gems/actionpack-7.0.4/lib/action_dispatch/request/utils.rb:95:in `action_encoding_template'", "  /Home/.rvm/gems/ruby-3.0.1/gems/actionpack-7.0.4/lib/action_dispatch/request/utils.rb:83:in `encode'", "  /Home/.rvm/gems/ruby-3.0.1/gems/actionpack-7.0.4/lib/action_dispatch/request/utils.rb:45:in `set_binary_encoding'", "  /Home/.rvm/gems/ruby-3.0.1/gems/actionpack-7.0.4/lib/action_dispatch/http/parameters.rb:68:in `path_parameters='", "  /Home/.rvm/gems/ruby-3.0.1/gems/actionpack-7.0.4/lib/action_dispatch/journey/router.rb:48:in `block in serve'", "  /Home/.rvm/gems/ruby-3.0.1/gems/actionpack-7.0.4/lib/action_dispatch/journey/router.rb:32:in `each'", "  /Home/.rvm/gems/ruby-3.0.1/gems/actionpack-7.0.4/lib/action_dispatch/journey/router.rb:32:in `serve'", "  /Home/.rvm/gems/ruby-3.0.1/gems/actionpack-7.0.4/lib/action_dispatch/routing/route_set.rb:852:in `call'", "  /Home/.rvm/gems/ruby-3.0.1/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'", "  /Home/.rvm/gems/ruby-3.0.1/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'", "  /Home/.rvm/gems/ruby-3.0.1/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'", "  /Home/.rvm/gems/ruby-3.0.1/gems/rack-2.2.4/lib/rack/tempfile_reaper.rb:15:in `call'", "  /Home/.rvm/gems/ruby-3.0.1/gems/rack-2.2.4/lib/rack/etag.rb:27:in `call'", "  /Home/.rvm/gems/ruby-3.0.1/gems/rack-2.2.4/lib/rack/conditional_get.rb:40:in `call'", "  /Home/.rvm/gems/ruby-3.0.1/gems/rack-2.2.4/lib/rack/head.rb:12:in `call'", "  /Home/.rvm/gems/ruby-3.0.1/gems/actionpack-7.0.4/lib/action_dispatch/http/permissions_policy.rb:38:in `call'", "  /Home/.rvm/gems/ruby-3.0.1/gems/actionpack-7.0.4/lib/action_dispatch/http/content_security_policy.rb:36:in `call'", "  /Home/.rvm/gems/ruby-3.0.1/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:266:in `context'", "  /Home/.rvm/gems/ruby-3.0.1/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:260:in `call'", "  /Home/.rvm/gems/ruby-3.0.1/gems/actionpack-7.0.4/lib/action_dispatch/middleware/cookies.rb:696:in `call'", "  /Home/.rvm/gems/ruby-3.0.1/gems/activerecord-7.0.4/lib/active_record/migration.rb:603:in `call'", "  /Home/.rvm/gems/ruby-3.0.1/gems/actionpack-7.0.4/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'", "  /Home/.rvm/gems/ruby-3.0.1/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:99:in `run_callbacks'", "  /Home/.rvm/gems/ruby-3.0.1/gems/actionpack-7.0.4/lib/action_dispatch/middleware/callbacks.rb:26:in `call'", "  /Home/.rvm/gems/ruby-3.0.1/gems/actionpack-7.0.4/lib/action_dispatch/middleware/executor.rb:14:in `call'", "  /Home/.rvm/gems/ruby-3.0.1/gems/actionpack-7.0.4/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'", "  /Home/.rvm/gems/ruby-3.0.1/gems/sentry-rails-5.5.0/lib/sentry/rails/rescued_exception_interceptor.rb:9:in `call'", "  /Home/.rvm/gems/ruby-3.0.1/gems/actionpack-7.0.4/lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'", "  /Home/.rvm/gems/ruby-3.0.1/gems/web-console-4.2.0/lib/web_console/middleware.rb:132:in `call_app'", "  /Home/.rvm/gems/ruby-3.0.1/gems/web-console-4.2.0/lib/web_console/middleware.rb:28:in `block in call'", "  /Home/.rvm/gems/ruby-3.0.1/gems/web-console-4.2.0/lib/web_console/middleware.rb:17:in `catch'", "  /Home/.rvm/gems/ruby-3.0.1/gems/web-console-4.2.0/lib/web_console/middleware.rb:17:in `call'", "  /Home/.rvm/gems/ruby-3.0.1/gems/sentry-ruby-5.5.0/lib/sentry/rack/capture_exceptions.rb:13:in `call'", "  /Home/.rvm/gems/ruby-3.0.1/gems/actionpack-7.0.4/lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'", "  /Home/.rvm/gems/ruby-3.0.1/gems/railties-7.0.4/lib/rails/rack/logger.rb:40:in `call_app'", "  /Home/.rvm/gems/ruby-3.0.1/gems/railties-7.0.4/lib/rails/rack/logger.rb:25:in `block in call'", "  /Home/.rvm/gems/ruby-3.0.1/gems/activesupport-7.0.4/lib/active_support/tagged_logging.rb:99:in `block in tagged'", "  /Home/.rvm/gems/ruby-3.0.1/[34178] Thread: TID-dj8 puma srv tp 005
```

I tried to debug it by editing the `token` method in `tokens_controller` but it's not even reaching that point.

### Expected behavior
It shouldn't hang.

### Actual behavior
The request hangs.

### System configuration

**Doorkeeper initializer**:

```ruby
Doorkeeper.configure do
  orm :active_record
  resource_owner_from_credentials do
    User.authenticate(params[:email], params[:password])
  end
  grant_flows %w[password]
  use_polymorphic_resource_owner
  access_token_expires_in 1.day
  use_refresh_token
  allow_blank_redirect_uri true
  skip_authorization do
    true
  end
end

```

**Ruby version**: `3.0.1`

**Gemfile.lock**:

<details>
  <summary>Gemfile.lock content</summary>
  
```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (7.0.4)
      actionpack (= 7.0.4)
      activesupport (= 7.0.4)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (7.0.4)
      actionpack (= 7.0.4)
      activejob (= 7.0.4)
      activerecord (= 7.0.4)
      activestorage (= 7.0.4)
      activesupport (= 7.0.4)
      mail (>= 2.7.1)
      net-imap
      net-pop
      net-smtp
    actionmailer (7.0.4)
      actionpack (= 7.0.4)
      actionview (= 7.0.4)
      activejob (= 7.0.4)
      activesupport (= 7.0.4)
      mail (~> 2.5, >= 2.5.4)
      net-imap
      net-pop
      net-smtp
      rails-dom-testing (~> 2.0)
    actionpack (7.0.4)
      actionview (= 7.0.4)
      activesupport (= 7.0.4)
      rack (~> 2.0, >= 2.2.0)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (7.0.4)
      actionpack (= 7.0.4)
      activerecord (= 7.0.4)
      activestorage (= 7.0.4)
      activesupport (= 7.0.4)
      globalid (>= 0.6.0)
      nokogiri (>= 1.8.5)
    actionview (7.0.4)
      activesupport (= 7.0.4)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activejob (7.0.4)
      activesupport (= 7.0.4)
      globalid (>= 0.3.6)
    activemodel (7.0.4)
      activesupport (= 7.0.4)
    activerecord (7.0.4)
      activemodel (= 7.0.4)
      activesupport (= 7.0.4)
    activestorage (7.0.4)
      actionpack (= 7.0.4)
      activejob (= 7.0.4)
      activerecord (= 7.0.4)
      activesupport (= 7.0.4)
      marcel (~> 1.0)
      mini_mime (>= 1.1.0)
    activesupport (7.0.4)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
    addressable (2.8.1)
      public_suffix (>= 2.0.2, < 6.0)
    bcrypt (3.1.18)
    bindex (0.8.1)
    bootsnap (1.13.0)
      msgpack (~> 1.2)
    builder (3.2.4)
    capybara (3.37.1)
      addressable
      matrix
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
    childprocess (4.1.0)
    concurrent-ruby (1.1.10)
    crass (1.0.6)
    debug (1.6.2)
      irb (>= 1.3.6)
      reline (>= 0.3.1)
    devise (4.8.1)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0)
      responders
      warden (~> 1.2.3)
    doorkeeper (5.6.0)
      railties (>= 5)
    dotenv (2.8.1)
    dotenv-rails (2.8.1)
      dotenv (= 2.8.1)
      railties (>= 3.2)
    erubi (1.11.0)
    globalid (1.0.0)
      activesupport (>= 5.0)
    i18n (1.12.0)
      concurrent-ruby (~> 1.0)
    importmap-rails (1.1.5)
      actionpack (>= 6.0.0)
      railties (>= 6.0.0)
    io-console (0.5.11)
    irb (1.4.2)
      reline (>= 0.3.0)
    jbuilder (2.11.5)
      actionview (>= 5.0.0)
      activesupport (>= 5.0.0)
    loofah (2.19.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (1.0.2)
    matrix (0.4.2)
    method_source (1.0.0)
    mini_mime (1.1.2)
    mini_portile2 (2.8.0)
    minitest (5.16.3)
    msgpack (1.6.0)
    net-imap (0.3.1)
      net-protocol
    net-pop (0.1.2)
      net-protocol
    net-protocol (0.1.3)
      timeout
    net-smtp (0.3.2)
      net-protocol
    nio4r (2.5.8)
    nokogiri (1.13.8)
      mini_portile2 (~> 2.8.0)
      racc (~> 1.4)
    nokogiri (1.13.8-arm64-darwin)
      racc (~> 1.4)
    nokogiri (1.13.8-x86_64-darwin)
      racc (~> 1.4)
    nokogiri (1.13.8-x86_64-linux)
      racc (~> 1.4)
    orm_adapter (0.5.0)
    paper_trail (13.0.0)
      activerecord (>= 5.2)
      request_store (~> 1.1)
    pg (1.4.4)
    public_suffix (5.0.0)
    puma (5.6.5)
      nio4r (~> 2.0)
    racc (1.6.0)
    rack (2.2.4)
    rack-cors (1.1.1)
      rack (>= 2.0.0)
    rack-test (2.0.2)
      rack (>= 1.3)
    rails (7.0.4)
      actioncable (= 7.0.4)
      actionmailbox (= 7.0.4)
      actionmailer (= 7.0.4)
      actionpack (= 7.0.4)
      actiontext (= 7.0.4)
      actionview (= 7.0.4)
      activejob (= 7.0.4)
      activemodel (= 7.0.4)
      activerecord (= 7.0.4)
      activestorage (= 7.0.4)
      activesupport (= 7.0.4)
      bundler (>= 1.15.0)
      railties (= 7.0.4)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.4.3)
      loofah (~> 2.3)
    railties (7.0.4)
      actionpack (= 7.0.4)
      activesupport (= 7.0.4)
      method_source
      rake (>= 12.2)
      thor (~> 1.0)
      zeitwerk (~> 2.5)
    rake (13.0.6)
    redis (4.8.0)
    regexp_parser (2.6.0)
    reline (0.3.1)
      io-console (~> 0.5)
    request_store (1.5.1)
      rack (>= 1.4)
    responders (3.0.1)
      actionpack (>= 5.0)
      railties (>= 5.0)
    rexml (3.2.5)
    rubyzip (2.3.2)
    selenium-webdriver (4.5.0)
      childprocess (>= 0.5, < 5.0)
      rexml (~> 3.2, >= 3.2.5)
      rubyzip (>= 1.2.2, < 3.0)
      websocket (~> 1.0)
    sentry-rails (5.5.0)
      railties (>= 5.0)
      sentry-ruby (~> 5.5.0)
    sentry-ruby (5.5.0)
      concurrent-ruby (~> 1.0, >= 1.0.2)
    sprockets (4.1.1)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.4.2)
      actionpack (>= 5.2)
      activesupport (>= 5.2)
      sprockets (>= 3.0.0)
    stimulus-rails (1.1.0)
      railties (>= 6.0.0)
    tailwindcss-rails (2.0.14)
      railties (>= 6.0.0)
    tailwindcss-rails (2.0.14-arm64-darwin)
      railties (>= 6.0.0)
    tailwindcss-rails (2.0.14-x86_64-darwin)
      railties (>= 6.0.0)
    tailwindcss-rails (2.0.14-x86_64-linux)
      railties (>= 6.0.0)
    thor (1.2.1)
    timeout (0.3.0)
    turbo-rails (1.3.0)
      actionpack (>= 6.0.0)
      activejob (>= 6.0.0)
      railties (>= 6.0.0)
    tzinfo (2.0.5)
      concurrent-ruby (~> 1.0)
    warden (1.2.9)
      rack (>= 2.0.9)
    web-console (4.2.0)
      actionview (>= 6.0.0)
      activemodel (>= 6.0.0)
      bindex (>= 0.4.0)
      railties (>= 6.0.0)
    webdrivers (5.2.0)
      nokogiri (~> 1.6)
      rubyzip (>= 1.3.0)
      selenium-webdriver (~> 4.0)
    websocket (1.2.9)
    websocket-driver (0.7.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    xpath (3.2.0)
      nokogiri (~> 1.8)
    zeitwerk (2.6.1)

PLATFORMS
  arm64-darwin-21
  ruby
  x86_64-darwin-21
  x86_64-linux

DEPENDENCIES
  bootsnap
  capybara
  debug
  devise
  doorkeeper
  dotenv-rails
  importmap-rails
  jbuilder
  paper_trail
  pg (~> 1.1)
  puma (~> 5.0)
  rack-cors
  rails (~> 7.0.4)
  redis (~> 4.0)
  selenium-webdriver
  sentry-rails
  sentry-ruby
  sprockets-rails
  stimulus-rails
  tailwindcss-rails
  turbo-rails
  tzinfo-data
  web-console
  webdrivers

RUBY VERSION
   ruby 3.0.1p64

BUNDLED WITH
   2.3.22
```
</details>

**Comment by nbulaj** [comment]
Hey @sradu . I;m not sure why it's happening, but could be that your app uses too many requests and puma (and your ) configuration couldn't into such throughput (or database create a lot of locks for example which blocks the server). It's hard to do something with it inside Doorkeeper itself

**Comment by sradu** [comment]
We worked around it a while back by proxying all client-side requests through one server endpoint.

Still, and I don't want to try this out, can I DoS anyone using doorkeeper if I just make a lot of requests that end up blocking all the available processes?

**Comment by nbulaj** [comment]
No idea to be honest. I think the same as with any other Rails app endpoint which interacts with the database (and especially uses database locks). So `rack-attack` and other solutions to the rest

**Comment by sradu** [comment]
OK sounds good. Will close the issue. Appreciate the conversion @nbulaj.
