### ISSUE TITLE
`rails generate doorkeeper:install` fails with `uninitialized constant ActiveRecord` for a non-ActiveRecord project

### ISSUE THREAD

**Issue by zedtux** [doorkeeper-gem/doorkeeper#1653]
### Steps to reproduce
1. Create a non-activerecord Rails application (Mongoid, Nobrainer or whatever other ORM than ActiveRecord)
2. Install the gem
3. Run the `rails generate doorkeeper:install` command

### Expected behavior
Doorkeeper should have see that ActiveRecord is unknown in my project, but I have added the `doorkeeper-rethinkdb` gem and should skip all the ActiveRecord code.

### Actual behavior
I got the following error:

```
/usr/local/bundle/gems/doorkeeper-5.6.6/lib/doorkeeper/orm/active_record/access_grant.rb:6:in `<module:Doorkeeper>': uninitialized constant ActiveRecord (NameError)
Did you mean?  ActiveModel
	from /usr/local/bundle/gems/doorkeeper-5.6.6/lib/doorkeeper/orm/active_record/access_grant.rb:5:in `<main>'
	from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
	from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /usr/local/bundle/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /usr/local/bundle/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
	from /usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/inflector/methods.rb:288:in `const_get'
	from /usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/inflector/methods.rb:288:in `block in constantize'
	from /usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/inflector/methods.rb:284:in `each'
	from /usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/inflector/methods.rb:284:in `inject'
	from /usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/inflector/methods.rb:284:in `constantize'
	from /usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/core_ext/string/inflections.rb:74:in `constantize'
	from /usr/local/bundle/gems/doorkeeper-5.6.6/lib/doorkeeper/config.rb:442:in `access_grant_model'
	from /usr/local/bundle/gems/doorkeeper-5.6.6/lib/doorkeeper/orm/active_record.rb:40:in `initialize_configured_associations'
	from /usr/local/bundle/gems/doorkeeper-5.6.6/lib/doorkeeper/orm/active_record.rb:32:in `run_hooks'
	from /usr/local/bundle/gems/doorkeeper-5.6.6/lib/doorkeeper.rb:164:in `run_orm_hooks'
	from /usr/local/bundle/gems/doorkeeper-5.6.6/lib/doorkeeper/engine.rb:24:in `block in <class:Engine>'
	from /usr/local/bundle/gems/activesupport-6.1.4.4/lib/active_support/callbacks.rb:427:in `instance_exec'
       ...
```

### System configuration

**Doorkeeper version**: `5.6.6`
**Ruby version**: `3.0.4`

**Comment by nbulaj** [comment]
hey @zedtux . How does your doorkeeper config looks like? It's weird that it tries to load AR if `orm :mongoid` configured

**Comment by zedtux** [comment]
My ORM is `rethinkdb`, but that doesn't really matter I guess, and at that moment I don't have a `doorkeeper.rb` initialiser since I have just added the `doorkeeper` gem to my `Gemfile`, ran `bundle` and wanted to run `rails generate doorkeeper:install` like [the documentation](https://doorkeeper.gitbook.io/guides/ruby-on-rails/getting-started) tells so.

**Comment by redross** [comment]
https://github.com/doorkeeper-gem/doorkeeper/issues/1653#issuecomment-1532599720

Yup, same issue for me. Added gem - can't run the rake task. Maybe doing something wrong, but clearly something is not clear in the documentation if I'm not the only one stumbling on this.

**Comment by Vineeth-Moturi** [comment]
Any solution, for this issue? Still getting when using with mongoid 8.1 and mongo server 7.0.7

**Comment by nbulaj** [comment]
Hello. Maybe anyone can check latest `main` branch if it's still an issue? With all the changes around lazy loading ORD dependent files

**Comment by 55728** [comment]
I tested `doorkeeper:install` on the latest `main` with two scenarios:

**1. Minimal (no ORM):**

```
rails new doorkeeper_test --skip-active-record --skip-test --skip-bundle
cd doorkeeper_test
# Gemfile: gem "doorkeeper", github: "doorkeeper-gem/doorkeeper", branch: "main"
bundle install
bin/rails generate doorkeeper:install
```

Result: generator completes successfully. ✅

**2. With Mongoid:**

```
rails new doorkeeper_mongoid_test --skip-active-record --skip-test --skip-bundle
cd doorkeeper_mongoid_test
# Gemfile: gem "doorkeeper", github: "doorkeeper-gem/doorkeeper", branch: "main"
#          gem "mongoid"
bundle install
bin/rails generate doorkeeper:install
```

Result: generator completes successfully. ✅

```
Ruby 4.0.2, Rails 8.0.5, Doorkeeper 5.9.0
```

The original issue was caused by eager loading of ORM-dependent files during engine initialization. This was resolved by the lazy loading changes introduced in #1804 and related PRs.

I believe this can be safely closed.

**Comment by nbulaj** [comment]
I'll close it for now. Please feel free to create a new one if we still have this issue. Thanks everyone!
