### ISSUE TITLE
in gitlab deploy doorkeeper error

### ISSUE THREAD

**Issue by letrath** [doorkeeper-gem/doorkeeper#694]
hello i am trying to install gitlab on a virtual ubuntu  which is working on power (ppc64el) according to the link:
https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/install/installation.md

But there is a step i cant pass,  
```
ronald@Ruby2:/home/git/gitlab$ sudo -u git -H bundle exec rake gitlab:env:info RAILS_ENV=production
rake aborted!
SyntaxError: /home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/doorkeeper-2.1.3/lib/doorkeeper/engine.rb:4: unknown type of %string
      app.config.filter_parameters += %i(client_secret code token)
                                         ^
/home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/doorkeeper-2.1.3/lib/doorkeeper/engine.rb:4: syntax error, unexpected $end
      app.config.filter_parameters += %i(client_secret code token)
                                         ^
/home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:247:in `require'
/home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:247:in `block in require'
/home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:232:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:247:in `require'
/home/git/gitlab/vendor/bundle/ruby/1.9.1/gems/doorkeeper-2.1.3/lib/doorkeeper.rb:2:in `<top (required)>'
/home/git/gitlab/config/application.rb:6:in `<top (required)>'
/home/git/gitlab/Rakefile:5:in `require'
/home/git/gitlab/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)
ronald@Ruby2:/home/git/gitlab$
```
Can any1 please help?
```
ronald@Ruby2:/home/git/gitlab$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [powerpc64le-linux]
ronald@Ruby2:/home/git/gitlab$ gem -v
2.4.5
```

**Comment by tute** [comment]
If you do `sudo ruby -v` it will be a different version. It seems like it's trying to use Ruby 1.9.

**Comment by letrath** [comment]
how can i fix it?i am new to ruby because

**Comment by tute** [comment]
How did you install Ruby 2.2? Through rbenv or rvm? You can install it as a superuser, doing:

```
sudo su # Logs you in as the super user
```

Then performing the same steps to set up the newer Ruby.

**Comment by letrath** [comment]
rbenv. oh ok. thnx
