### ISSUE TITLE
Doorkeeper::OAuth::Helpers::UniqueToken not found

### ISSUE THREAD

**Issue by daniyal229** [doorkeeper-gem/doorkeeper#775]
Error occurs while creating an access token using 

`Doorkeeper::AccessToken.create! application_id: application.id, user_id: resource.id`

`Doorkeeper::OAuth::Helpers::UniqueToken` not found

**Comment by tute** [comment]
For what version of doorkeeper? How exactly can I replicate this issue? Please see http://yourbugreportneedsmore.info/.

**Comment by quolpr** [comment]
I have the same error and I understand why it is happening.
The stacktraces is so:
```
Doorkeeper::Errors::TokenGeneratorNotFound: Doorkeeper::OAuth::Helpers::UniqueToken not found
	from /home/quolpr/.rvm/gems/ruby-2.2-head/gems/doorkeeper-3.1.0/lib/doorkeeper/models/access_token_mixin.rb:139:in `rescue in generate_token'
	from /home/quolpr/.rvm/gems/ruby-2.2-head/gems/doorkeeper-3.1.0/lib/doorkeeper/models/access_token_mixin.rb:132:in `generate_token'
	from /home/quolpr/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:432:in `block in make_lambda'
	from /home/quolpr/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:145:in `call'
	from /home/quolpr/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:145:in `block in halting_and_conditional'
	from /home/quolpr/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:504:in `call'
	from /home/quolpr/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:504:in `block in call'
	from /home/quolpr/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:504:in `each'
	from /home/quolpr/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:504:in `call'
	from /home/quolpr/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
	from /home/quolpr/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_validation_callbacks'
	from /home/quolpr/.rvm/gems/ruby-2.2-head/gems/activemodel-4.2.5/lib/active_model/validations/callbacks.rb:113:in `run_validations!'
	from /home/quolpr/.rvm/gems/ruby-2.2-head/gems/activemodel-4.2.5/lib/active_model/validations.rb:337:in `valid?'
	from /home/quolpr/.rvm/gems/ruby-2.2-head/gems/activerecord-4.2.5/lib/active_record/validations.rb:58:in `valid?'
	from /home/quolpr/.rvm/gems/ruby-2.2-head/gems/activerecord-4.2.5/lib/active_record/validations.rb:83:in `perform_validations'
	from /home/quolpr/.rvm/gems/ruby-2.2-head/gems/activerecord-4.2.5/lib/active_record/validations.rb:43:in `save!'
... 22 levels...
	from /home/quolpr/.rvm/gems/ruby-2.2-head/gems/railties-4.2.5/lib/rails/commands/console.rb:9:in `start'
	from /home/quolpr/.rvm/gems/ruby-2.2-head/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/quolpr/.rvm/gems/ruby-2.2-head/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/quolpr/.rvm/gems/ruby-2.2-head/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/quolpr/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /home/quolpr/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/quolpr/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/quolpr/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /home/quolpr/projects/upwork/neu_one/beaconhub/bin/rails:9:in `<top (required)>'
	from /home/quolpr/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
	from /home/quolpr/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/quolpr/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/quolpr/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
	from /home/quolpr/.rvm/rubies/ruby-2.2-head/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/quolpr/.rvm/rubies/ruby-2.2-head/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```
In the documentation you said, that you can rename `resource_owner_id` field to `user_id`, but it will raise error in `access_token_mixin.rb`:
```ruby
    def generate_token
      generator = Doorkeeper.configuration.access_token_generator.constantize
      self.token = generator.generate(resource_owner_id: resource_owner_id <<< because of this,
                                      scopes: scopes, application: application,
                                      expires_in: expires_in)
    rescue NoMethodError
      raise Errors::UnableToGenerateToken, "#{generator} does not respond to `.generate`."
    rescue NameError
      raise Errors::TokenGeneratorNotFound, "#{generator} not found"
    end
```

**Comment by quolpr** [comment]
The version is 3.1.0

**Comment by quolpr** [comment]
The solution is to configure foreign key manually:
```ruby
add_foreign_key :oauth_access_tokens, :users, column: :resource_owner_id
add_foreign_key :oauth_access_grants, :users, column: :resource_owner_id
```
And I think that error handling is not so good.

**Comment by tute** [comment]
Yep, error message could be better. Thanks for documenting this for people getting this error, and if anyone would like to improve the error message, please go ahead. Thanks!

**Comment by SirRawlins** [comment]
Hey Gang, I'm getting the same error today using 3.1.0 - can you confirm what the situation is with this? Should I not have modified the migration to change the column names?

**Comment by tute** [comment]
How did you change the column names?
