### ISSUE TITLE
NoMethodError (undefined method `refresh_token_revoked_on_use?' for Doorkeeper::AccessToken:Class)

### ISSUE THREAD

**Issue by phinfonet** [doorkeeper-gem/doorkeeper#852]
Hello!

I'm using dorkeeper with rails 5, using the git repo and get this error when try to authorize with bearer token.
have any specific configuration to use that, or it could be a bug?

Completed 500 Internal Server Error in 39ms

  
NoMethodError (undefined method `refresh_token_revoked_on_use?' for Doorkeeper::AccessToken:Class):
  
/home/phinfonet/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/doorkeeper-f2871c20a4d9/lib/doorkeeper/models/concerns/revocable.rb:26:in `refresh_token_revoked_on_use?'
/home/phinfonet/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/doorkeeper-f2871c20a4d9/lib/doorkeeper/models/concerns/revocable.rb:13:in `revoke_previous_refresh_token!'

**Comment by phinfonet** [comment]
fixed in https://github.com/doorkeeper-gem/doorkeeper-mongodb/pull/15
