### ISSUE TITLE
generate migration for rails v 5.1.0

### ISSUE THREAD

**Issue by frostmark** [doorkeeper-gem/doorkeeper#963]
```rails aborted!
StandardError: An error has occurred, all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateDoorkeeperTables < ActiveRecord::Migration[4.2]
/home/another/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0/lib/active_record/migration.rb:525:in `inherited'
/home/another/my_projects/smartdating/api/db/migrate/20170507084215_create_doorkeeper_tables.rb:1:in `<top (required)>'
/home/another/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
/home/another/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `block in require'
/home/another/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/another/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
/home/another/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0/lib/active_record/migration.rb:962:in `load_migration'
/home/another/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0/lib/active_record/migration.rb:958:in `migration'
/home/another/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0/lib/active_record/migration.rb:953:in `disable_ddl_transaction'
/home/another/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0/lib/active_record/migration.rb:1305:in `use_transaction?'
/home/another/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0/lib/active_record/migration.rb:1297:in `ddl_transaction'
/home/another/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/home/another/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/home/another/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0/lib/active_record/migration.rb:1200:in `each'
/home/another/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/home/another/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0/lib/active_record/migration.rb:1148:in `block in migrate'
/home/another/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0/lib/active_record/migration.rb:1317:in `with_advisory_lock'
/home/another/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0/lib/active_record/migration.rb:1148:in `migrate'
/home/another/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0/lib/active_record/migration.rb:1007:in `up'
/home/another/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0/lib/active_record/migration.rb:985:in `migrate'
/home/another/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/home/another/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.0/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/home/another/.rvm/gems/ruby-2.4.1/gems/railties-5.1.0/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/home/another/.rvm/gems/ruby-2.4.1/gems/railties-5.1.0/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/another/.rvm/gems/ruby-2.4.1/gems/railties-5.1.0/lib/rails/command.rb:46:in `invoke'
/home/another/.rvm/gems/ruby-2.4.1/gems/railties-5.1.0/lib/rails/commands.rb:16:in `<top (required)>'
/home/another/my_projects/smartdating/api/bin/rails:9:in `require'
/home/another/my_projects/smartdating/api/bin/rails:9:in `<top (required)>'
/home/another/.rvm/gems/ruby-2.4.1/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `load'
/home/another/.rvm/gems/ruby-2.4.1/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `call'
/home/another/.rvm/gems/ruby-2.4.1/gems/spring-2.0.1/lib/spring/client/command.rb:7:in `call'
/home/another/.rvm/gems/ruby-2.4.1/gems/spring-2.0.1/lib/spring/client.rb:30:in `run'
/home/another/.rvm/gems/ruby-2.4.1/gems/spring-2.0.1/bin/spring:49:in `<top (required)>'
/home/another/.rvm/gems/ruby-2.4.1/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `load'
/home/another/.rvm/gems/ruby-2.4.1/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `<top (required)>'
/home/another/my_projects/smartdating/api/bin/spring:15:in `require'
/home/another/my_projects/smartdating/api/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
``` #

**Comment by tostasqb** [comment]
Same happening for Rails 5.1.1. 
I'm specifying this on the Gemfile

**Comment by tostasqb** [comment]
Workaround would be to specify the version on the migration:

`class CreateDoorkeeperTables < ActiveRecord::Migration[5.1]`

**Comment by frostmark** [comment]
@tostasqb thx

**Comment by MCodyB** [comment]
Granted the fix is easy enough but shouldn't this remain an open issue until it's fixed? If only so you can search it from the open issues.
