### ISSUE TITLE
NameError (uninitialized constant Mongoid::Relations::Cascading::DeleteAll):

### ISSUE THREAD

**Issue by S-Cardenas** [doorkeeper-gem/doorkeeper#971]
Hello,

I've been receiving the error below when trying to delete one of my applications from http://localhost:3000/api/v1/oauth/applications. 

```
Started DELETE "/api/v1/oauth/applications/5930bd2aa54dd321f7248178" for ::1 at 2017-06-01 21:53:22 -0400
Processing by Doorkeeper::ApplicationsController#destroy as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"+IxdEDUYW65Hj99VUqdJ/rydjZjJE8CIFy7El5KuuZ0rf36wLE0M4qJxBUL61D1IeRW+VvgWw1o9ckXxpHBkVw==", "commit"=>"Destroy", "id"=>"5930bd2aa54dd321f7248178"}
MONGODB | localhost:27017 | playco_development.find | STARTED | {"find"=>"oauth_applications", "filter"=>{"_id"=>BSON::ObjectId('5930bd2aa54dd321f7248178')}}
MONGODB | localhost:27017 | playco_development.find | SUCCEEDED | 0.000784s
Completed 500 Internal Server Error in 9ms

NameError (uninitialized constant Mongoid::Relations::Cascading::DeleteAll):
  activesupport (4.2.8) lib/active_support/inflector/methods.rb:263:in `const_get'
  activesupport (4.2.8) lib/active_support/inflector/methods.rb:263:in `block in constantize'
  activesupport (4.2.8) lib/active_support/inflector/methods.rb:259:in `each'
  activesupport (4.2.8) lib/active_support/inflector/methods.rb:259:in `inject'
  activesupport (4.2.8) lib/active_support/inflector/methods.rb:259:in `constantize'
  activesupport (4.2.8) lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
  mongoid (5.2.1) lib/mongoid/relations/metadata.rb:98:in `cascade_strategy'
  mongoid (5.2.1) lib/mongoid/relations/cascading.rb:30:in `block in cascade!'
```

Here are the gems I am using that are pertinent to mongoid and rails:
```
gem 'rails', '4.2.8'
gem 'mongoid', '~> 5.2.1'gem 'doorkeeper-mongodb', github: 'doorkeeper-gem/doorkeeper-mongodb'
gem "doorkeeper-grants_assertion", github: "doorkeeper-gem/doorkeeper-grants_assertion"
```

This only happens when trying to 'destroy' an existing application from the UI.

Any help would be greatly appreciated.

**Comment by S-Cardenas** [comment]
The problem stemmed from `gem 'doorkeeper-mongodb'` requiring `gem 'doorkeeper'` at version >= 4.00. A version of `gem 'doorkeeper'` greater than v3.1.0 has a `dependent: :delete_all` association (see doorkeeper/lib/doorkeeper/models/application_mixin.rb within the doorkeeper gem file). A cascading relation of `:delete_all` is not supported in any of version of Mongoid to date and raises the `NameError` exception.

I got around this by requiring `gem 'doorkeeper', '~> 3.1.0'`. However this caused a gem dependency issue with `gem 'doorkeeper-grants_assertion'` which I fixed by requesting a specific commit version in my gem file as seen below:

    gem 'mongoid', '~> 5.1.0'
    gem 'doorkeeper-mongodb', github: 'doorkeeper-gem/doorkeeper-mongodb'
    gem 'doorkeeper', '~> 3.1.0'
    gem 'doorkeeper-grants_assertion', github: "doorkeeper-gem/doorkeeper-
    grants_assertion", :ref => 'f4391f2f07d96845db0d9dd6889f58d4bd4d23bb'

**Comment by nbulaj** [comment]
So it is not a problem of doorkeeper gem, it is a problem of doorkeeper-mongodb. And the last one requires some fixes for `delete all` operation. Concerning doorkeeper gem (and problem dependence from it's version) - need to look at the models of this versions and `dependent` option.

**Comment by maclover7** [comment]
@S-Cardenas Are you sure `delete_all` is not supported in mongoid? I personally don't use it, but it looks like the method is referenced many times in the codebase, and there are even some [tests](https://github.com/mongodb/mongoid/blob/master/spec/mongoid/association/depending_spec.rb#L359) for it.

**Comment by hiroshi** [comment]
https://github.com/mongodb/mongoid/blob/master/spec/mongoid/association/depending_spec.rb does not seem to exist on the current latest release v6.2.0
https://github.com/mongodb/mongoid/find/v6.2.0

https://jira.mongodb.org/browse/MONGOID-4442
It seems they will add `delete_all` for v7.0

**Comment by hiroshi** [comment]
For Rails 5.x and mongoid 6.x users,
doorkeeper 3.1.0 cannot be used because it uses removed `before_action` for controllers.

doorkeeper introduced `dependent: :delete_all` in this commit: https://github.com/doorkeeper-gem/doorkeeper/commit/cc269ef052c0445662eda18623749d3ba67fb33d
v4.2.5 or later are affected.
Form https://rubygems.org/gems/doorkeeper, possible latest version of the gem is v4.2.0.
It works for me so far.

**Comment by S-Cardenas** [comment]
@maclover7 cascading `delete_all` is not supported for the original version of mongoid I was originally using (5.2.1).
