### ISSUE TITLE
NoMethodError in Doorkeeper::AuthorizationsController#new

### ISSUE THREAD

**Issue by jraczak** [doorkeeper-gem/doorkeeper#980]
I've configured according to the documentation. I'm using Rails 5.1, `devise_token_auth`, and `doorkeeper`. When I hit the `oauth/authorize` endpoint (via Postman or browser), I get:

`NoMethodError in Doorkeeper::AuthorizationsController#new` 

error triggered here:

```
def matching_token?
      AccessToken.matching_token_for pre_auth.client,
                                     current_resource_owner.id,
                                     pre_auth.scopes
    end
```

I'm not sure what code would be helpful because config is in so many different places, but please tell me what would be helpful and I'll post it directly. Otherwise the files can be seen here, on the `doorkeeper` branch:

https://github.com/jraczak/flow-api/tree/doorkeeper

**Comment by maclover7** [comment]
@jraczak Can you please post the full error backtrace? Thanks!

**Comment by jraczak** [comment]
@maclover7 Thanks for the quick reply and really sorry for the delay, I missed the notification email. Here's the trace.

```
Started GET "/oauth/authorize?client_id=3a866a9649d894bf61a262cfcf7ce74b9d22b81e85ac177c735258657bd256c6&scope=&state=9000151&redirect_uri=https%3A%2F%2Fwww.getpostman.com%2Foauth2%2Fcallback&response_type=code" for 127.0.0.1 at 2017-08-02 18:06:24 -0700
Processing by Doorkeeper::AuthorizationsController#new as HTML
  Parameters: {"client_id"=>"3a866a9649d894bf61a262cfcf7ce74b9d22b81e85ac177c735258657bd256c6", "scope"=>"", "state"=>"9000151", "redirect_uri"=>"https://www.getpostman.com/oauth2/callback", "response_type"=>"code"}
  Doorkeeper::Application Load (1.2ms)  SELECT  "oauth_applications".* FROM "oauth_applications" WHERE "oauth_applications"."uid" = $1 LIMIT $2  [["uid", "3a866a9649d894bf61a262cfcf7ce74b9d22b81e85ac177c735258657bd256c6"], ["LIMIT", 1]]
Completed 500 Internal Server Error in 18ms (ActiveRecord: 10.0ms)


  
NoMethodError (undefined method `id' for nil:NilClass):
  
doorkeeper (4.2.6) app/controllers/doorkeeper/authorizations_controller.rb:31:in `matching_token?'
doorkeeper (4.2.6) app/controllers/doorkeeper/authorizations_controller.rb:7:in `new'
actionpack (5.1.2) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.1.2) lib/abstract_controller/base.rb:186:in `process_action'
actionpack (5.1.2) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.1.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.1.2) lib/active_support/callbacks.rb:131:in `run_callbacks'
actionpack (5.1.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.1.2) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.1.2) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.2) lib/active_support/notifications.rb:166:in `instrument'
actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.1.2) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
activerecord (5.1.2) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
actionpack (5.1.2) lib/abstract_controller/base.rb:124:in `process'
actionview (5.1.2) lib/action_view/rendering.rb:30:in `process'
actionpack (5.1.2) lib/action_controller/metal.rb:189:in `dispatch'
actionpack (5.1.2) lib/action_controller/metal.rb:253:in `dispatch'
actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:31:in `serve'
actionpack (5.1.2) lib/action_dispatch/journey/router.rb:46:in `block in serve'
actionpack (5.1.2) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.2) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:832:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.3) lib/rack/etag.rb:25:in `call'
rack (2.0.3) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.3) lib/rack/head.rb:12:in `call'
rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.1.2) lib/active_record/migration.rb:556:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.2) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.2) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.3) lib/rack/method_override.rb:22:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.2) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
railties (5.1.2) lib/rails/engine.rb:522:in `call'
puma (3.9.1) lib/puma/configuration.rb:224:in `call'
puma (3.9.1) lib/puma/server.rb:602:in `handle_request'
puma (3.9.1) lib/puma/server.rb:435:in `process_client'
puma (3.9.1) lib/puma/server.rb:299:in `block in run'
puma (3.9.1) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by f3ndot** [comment]
I'm also encountering this issue in Rails 5.1.3.

It appears AuthorizationsController spec is missing the `authorization_code` grant flow test case.

I'll investigate further and see if I can put up a PR

**Comment by f3ndot** [comment]
@jraczak so it looks like its assumed in Doorkeeper that `GET /oauth/authorize` is called under the assumption that `current_resource_owner` is set. It makes sense that this route is meant to render an HTML view to prompt the user approval/denial of the OAuth app wanting to connect to it.

Per the README, make sure you define in your initializer the `resource_owner_authenticator` block so Doorkeeper can resolve the resource owner from the active session:

```ruby
Doorkeeper.configure do
  resource_owner_authenticator do
    User.find_by_id(session[:current_user_id]) || redirect_to(login_url)
  end
end
```

If you're like me and using Doorkeeper as an API under a microservice away from the actual business application then you're going to have to get a bit creative 😃

**Comment by nbulaj** [comment]
Hi @f3ndot . Thanks for research :)

@jraczak did you solve your problem? If not, could you provide your doorkeeper initializer ?

**Comment by nbulaj** [comment]
Closing due to lack of activity. Feel free to reopen this issue if issue still exists.

**Comment by leechunhoe** [comment]
I encountered similar issue though what I got is `undefined method 'unshift' for nil:NilClass`.
